<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AttoriTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('attori')->delete();

        \DB::table('attori')->insert([
            0 => [
                'id' => 1,
                'referente_id' => null,
                'tipo' => 'fornaio',
                'nome' => 'Massimo',
                'comune' => 'Cesano Maderno',
                'ragione_sociale' => 'Il Piccolo Forno',
                'indirizzo' => 'via Monte Rosa',
                'created_at' => '2017-03-15 11:42:18',
                'updated_at' => null,
            ],
            1 => [
                'id' => 2,
                'referente_id' => null,
                'tipo' => 'fornaio',
                'nome' => 'Colombo',
                'comune' => 'Bellinzago Lombardo',
                'ragione_sociale' => 'F.lli Colombo',
                'indirizzo' => '',
                'created_at' => '2017-03-15 11:42:18',
                'updated_at' => null,
            ],
            2 => [
                'id' => 3,
                'referente_id' => null,
                'tipo' => 'fornaio',
                'nome' => 'Franca',
                'comune' => 'Seregno',
                'ragione_sociale' => 'Il Pane di Franca',
                'indirizzo' => 'via Tenca',
                'created_at' => '2017-03-15 11:42:18',
                'updated_at' => null,
            ],
            3 => [
                'id' => 4,
                'referente_id' => null,
                'tipo' => 'fornaio',
                'nome' => 'Emilio',
                'comune' => '',
                'ragione_sociale' => '',
                'indirizzo' => '',
                'created_at' => '2017-03-15 11:42:18',
                'updated_at' => null,
            ],
            4 => [
                'id' => 5,
                'referente_id' => null,
                'tipo' => 'fornaio',
                'nome' => 'Giona',
                'comune' => 'Rovagnate',
                'ragione_sociale' => 'C.na Bagaggera',
                'indirizzo' => '',
                'created_at' => '2017-03-15 11:42:18',
                'updated_at' => null,
            ],
            5 => [
                'id' => 14,
                'referente_id' => 0,
                'tipo' => 'gas',
                'nome' => 'GAS Cernusco',
                'comune' => 'Cernusco Sul Naviglio',
                'ragione_sociale' => '',
                'indirizzo' => '',
                'created_at' => '2017-03-15 11:42:18',
                'updated_at' => null,
            ],
            6 => [
                'id' => 13,
                'referente_id' => 0,
                'tipo' => 'gas',
                'nome' => 'GAS Cassina',
                'comune' => 'Cassina De’ Pecchi',
                'ragione_sociale' => '',
                'indirizzo' => '',
                'created_at' => '2017-03-15 11:42:18',
                'updated_at' => null,
            ],
            7 => [
                'id' => 12,
                'referente_id' => 0,
                'tipo' => 'gas',
                'nome' => 'GAS Carate Basso',
                'comune' => 'Carate Brianza',
                'ragione_sociale' => '',
                'indirizzo' => '',
                'created_at' => '2017-03-15 11:42:18',
                'updated_at' => null,
            ],
            8 => [
                'id' => 11,
                'referente_id' => 0,
                'tipo' => 'gas',
                'nome' => 'GAS Carate Alto',
                'comune' => 'Carate Brianza',
                'ragione_sociale' => '',
                'indirizzo' => '',
                'created_at' => '2017-03-15 11:42:18',
                'updated_at' => null,
            ],
            9 => [
                'id' => 10,
                'referente_id' => 0,
                'tipo' => 'gas',
                'nome' => 'GAS Cent coo cent cr',
                'comune' => 'Brugherio',
                'ragione_sociale' => '',
                'indirizzo' => '',
                'created_at' => '2017-03-15 11:42:18',
                'updated_at' => null,
            ],
            10 => [
                'id' => 9,
                'referente_id' => 0,
                'tipo' => 'gas',
                'nome' => 'GAS Biassono',
                'comune' => 'Biassono',
                'ragione_sociale' => '',
                'indirizzo' => '',
                'created_at' => '2017-03-15 11:42:18',
                'updated_at' => null,
            ],
            11 => [
                'id' => 8,
                'referente_id' => 0,
                'tipo' => 'gas',
                'nome' => 'GAS Basiano',
                'comune' => 'Basiano',
                'ragione_sociale' => '',
                'indirizzo' => '',
                'created_at' => '2017-03-15 11:42:18',
                'updated_at' => null,
            ],
            12 => [
                'id' => 7,
                'referente_id' => 0,
                'tipo' => 'gas',
                'nome' => 'GAS Bargassina',
                'comune' => 'Barlassina',
                'ragione_sociale' => '',
                'indirizzo' => '',
                'created_at' => '2017-03-15 11:42:18',
                'updated_at' => null,
            ],
            13 => [
                'id' => 6,
                'referente_id' => 0,
                'tipo' => 'gas',
                'nome' => 'GAS Agrate',
                'comune' => 'Agrate Brianza',
                'ragione_sociale' => '',
                'indirizzo' => '',
                'created_at' => '2017-03-15 11:42:18',
                'updated_at' => null,
            ],
            14 => [
                'id' => 15,
                'referente_id' => 0,
                'tipo' => 'gas',
                'nome' => 'GAS ConSenso',
                'comune' => 'Cesano Maderno',
                'ragione_sociale' => '',
                'indirizzo' => '',
                'created_at' => '2017-03-15 11:42:18',
                'updated_at' => null,
            ],
            15 => [
                'id' => 16,
                'referente_id' => 0,
                'tipo' => 'gas',
                'nome' => 'GAS Concorezzo-Vimer',
                'comune' => 'Concorezzo-Vimercate',
                'ragione_sociale' => '',
                'indirizzo' => '',
                'created_at' => '2017-03-15 11:42:18',
                'updated_at' => null,
            ],
            16 => [
                'id' => 17,
                'referente_id' => 0,
                'tipo' => 'gas',
                'nome' => 'GAS La Lumachina',
                'comune' => 'Desio',
                'ragione_sociale' => '',
                'indirizzo' => '',
                'created_at' => '2017-03-15 11:42:18',
                'updated_at' => null,
            ],
            17 => [
                'id' => 18,
                'referente_id' => 0,
                'tipo' => 'gas',
                'nome' => 'GAS Gorgonzola',
                'comune' => 'Gorgonzola',
                'ragione_sociale' => '',
                'indirizzo' => '',
                'created_at' => '2017-03-15 11:42:18',
                'updated_at' => null,
            ],
            18 => [
                'id' => 19,
                'referente_id' => 0,
                'tipo' => 'gas',
                'nome' => 'GAS Mezzago',
                'comune' => 'Mezzago',
                'ragione_sociale' => '',
                'indirizzo' => '',
                'created_at' => '2017-03-15 11:42:18',
                'updated_at' => null,
            ],
            19 => [
                'id' => 20,
                'referente_id' => 0,
                'tipo' => 'gas',
                'nome' => 'GAS S.Fruttuoso',
                'comune' => 'Monza',
                'ragione_sociale' => '',
                'indirizzo' => '',
                'created_at' => '2017-03-15 11:42:18',
                'updated_at' => null,
            ],
            20 => [
                'id' => 21,
                'referente_id' => 0,
                'tipo' => 'gas',
                'nome' => 'GAS Seveso',
                'comune' => 'Seveso',
                'ragione_sociale' => '',
                'indirizzo' => '',
                'created_at' => '2017-03-15 11:42:18',
                'updated_at' => null,
            ],
            21 => [
                'id' => 22,
                'referente_id' => 0,
                'tipo' => 'gas',
                'nome' => 'GAS Pachamama',
                'comune' => 'Vedano',
                'ragione_sociale' => '',
                'indirizzo' => '',
                'created_at' => '2017-03-15 11:42:18',
                'updated_at' => null,
            ],
            22 => [
                'id' => 23,
                'referente_id' => 0,
                'tipo' => 'gas',
                'nome' => 'GAS F.Motta',
                'comune' => 'Villasanta',
                'ragione_sociale' => '',
                'indirizzo' => '',
                'created_at' => '2017-03-15 11:42:18',
                'updated_at' => null,
            ],
            23 => [
                'id' => 24,
                'referente_id' => null,
                'tipo' => 'gas',
                'nome' => 'GAS Cornate',
                'comune' => 'Cornate D\'Adda',
                'ragione_sociale' => '',
                'indirizzo' => '',
                'created_at' => '2017-03-15 11:42:18',
                'updated_at' => null,
            ],
        ]);

    }
}
